# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'restaurant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for restaurant
pod 'Alamofire'

  target 'restaurantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'restaurantUITests' do
    # Pods for testing
  end

end
