# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'hollyfood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hollyfood
  pod 'Alamofire'

end
